model_list:
- model_name: gpt-4
  display_name: GPT-4 (gpt-4)
  litellm_params:
    model: openai/gpt-4
    api_key: os.environ/OPENAI_API_KEY
- model_name: gpt-4o
  display_name: GPT-4o
  litellm_params:
    model: openai/gpt-4o
    api_key: os.environ/OPENAI_API_KEY
- model_name: gpt-4o-mini
  display_name: GPT-4o Mini
  litellm_params:
    model: openai/gpt-4o-mini
    api_key: os.environ/OPENAI_API_KEY
- model_name: gpt-3.5-turbo
  display_name: GPT-3.5 Turbo
  litellm_params:
    model: openai/gpt-3.5-turbo
    api_key: os.environ/OPENAI_API_KEY
- model_name: claude-3-opus
  display_name: Claude 3 Opus
  litellm_params:
    model: anthropic/claude-3-opus-20240229
    api_key: os.environ/ANTHROPIC_API_KEY
- model_name: claude-3-sonnet
  display_name: Claude 3 Sonnet
  litellm_params:
    model: anthropic/claude-3-5-sonnet-20240620
    api_key: os.environ/ANTHROPIC_API_KEY
- model_name: claude-3-5-sonnet
  display_name: Claude 3.5 Sonnet
  litellm_params:
    model: anthropic/claude-3-5-sonnet-20240620
    api_key: os.environ/ANTHROPIC_API_KEY
- model_name: claude-3-haiku
  display_name: Claude 3 Haiku
  litellm_params:
    model: anthropic/claude-3-haiku-20240307
    api_key: os.environ/ANTHROPIC_API_KEY
- model_name: gemini-1.5-pro
  display_name: Gemini 1.5 Pro
  litellm_params:
    model: gemini/gemini-pro
    api_key: os.environ/GOOGLE_API_KEY
- model_name: gemini-1.5-flash
  display_name: Gemini 1.5 Flash
  litellm_params:
    model: gemini/gemini-pro-vision
    api_key: os.environ/GOOGLE_API_KEY
- model_name: qwen2.5
  display_name: qwen2.5:0.5b (local)
  litellm_params:
    model: ollama/qwen2.5:0.5b
    api_base: http://ollama:11434
- model_name: qwen2.5-7b
  display_name: qwen2.5:7b (local)
  litellm_params:
    model: ollama/qwen2.5:7b
    api_base: http://ollama:11434
- model_name: llama31-taidelx-8b-32k
  display_name: Llama 3.1 TaideLX 8B-32K (Taiwan)
  litellm_params:
    model: openai/llama31-taidelx-8b-32k
    api_base: https://afspod-llm-api.dginfra.gov.tw/projects/392a1838-7af3-4679-8360-c0e24b4bcf8f/api/models
    api_key: 1191d4e5-f737-4f7c-b3b5-e80eeac656b5
- model_name: llama33-ffm-70b-32k
  display_name: Llama 3.3 FFM 70B-32K (Taiwan)
  litellm_params:
    model: openai/llama33-ffm-70b-32k
    api_base: https://afspod-llm-api.dginfra.gov.tw/projects/392a1838-7af3-4679-8360-c0e24b4bcf8f/api/models
    api_key: 1191d4e5-f737-4f7c-b3b5-e80eeac656b5
- model_name: llama31-foxbrain-70b-32k
  display_name: Llama 3.1 FoxBrain 70B-32K (Taiwan)
  litellm_params:
    model: openai/llama31-foxbrain-70b-32k
    api_base: https://afspod-llm-api.dginfra.gov.tw/projects/392a1838-7af3-4679-8360-c0e24b4bcf8f/api/models
    api_key: 1191d4e5-f737-4f7c-b3b5-e80eeac656b5
- model_name: llama3-taiwan-70b-8k
  display_name: Llama 3 Taiwan 70B-8K (Taiwan)
  litellm_params:
    model: openai/llama3-taiwan-70b-8k
    api_base: https://afspod-llm-api.dginfra.gov.tw/projects/392a1838-7af3-4679-8360-c0e24b4bcf8f/api/models
    api_key: 1191d4e5-f737-4f7c-b3b5-e80eeac656b5
- model_name: llama32-ffm-11b-v-32k
  display_name: Llama 3.2 FFM 11B Vision-32K (Taiwan)
  litellm_params:
    model: openai/llama32-ffm-11b-v-32k
    api_base: https://afspod-llm-api.dginfra.gov.tw/projects/392a1838-7af3-4679-8360-c0e24b4bcf8f/api/models
    api_key: 1191d4e5-f737-4f7c-b3b5-e80eeac656b5
litellm_settings:
  drop_params: true
  set_verbose: true
  cache: false
general_settings:
  master_key: sk-1234
  database_url: os.environ/DATABASE_URL
  ui_access_mode: admin
  store_model_in_db: true
